version: 2.1

# Define reusable executors
executors:
  node-executor:
    docker:
      - image: cimg/node:20.18.2
    working_directory: ~/repo

# Define jobs
jobs:
  install-dependencies:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

  build-and-test-db-core:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Build @db-core
          command: cd packages/db-core && npm run build
      - run:
          name: Test @db-core
          command: cd packages/db-core && npm run test

  build-and-test-admin-panel:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Build @admin-panel-service
          command: cd apps/admin-panel-service && npm run build
      - run:
          name: Test @admin-panel-service
          command: cd apps/admin-panel-service && npm run test

# Define workflows
workflows:
  version: 2
  build-and-test:
    jobs:
      - install-dependencies
      - build-and-test-db-core:
          requires:
            - install-dependencies
      - build-and-test-admin-panel:
          requires:
            - install-dependencies